require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'iChant' do

  # React Native Maps dependencies

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'RealmJS', :path => '../node_modules/realm'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'iChantTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_react_native!()

#  post_install do |installer|
##    react_native_post_install(installer)
#    react_native_post_install
#  end
end
